//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dksh.ePOD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dksh.ePOD.Resources.GeneralResource", typeof(GeneralResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Company have a whistleblowing channel which is extended to all of its employees?.
        /// </summary>
        public static string Aware_MY {
            get {
                return ResourceManager.GetString("Aware_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the Company aware of any conflict of interest in doing business with DKSH, including any of its owners/shareholders, directors or personnel?.
        /// </summary>
        public static string Aware_VN {
            get {
                return ResourceManager.GetString("Aware_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified copy of business license/registration (from SSM/CCM or Form D), Form 9, Form 13,Form 24 and Form 49, Certificatie of registration of LLP, Memorandum and Articles of Association/Constitution/CoSec Confirmation New Act Sec21.
        /// </summary>
        public static string BusinessReg_MY {
            get {
                return ResourceManager.GetString("BusinessReg_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified copy of business license/registration.
        /// </summary>
        public static string BusinessReg_VN {
            get {
                return ResourceManager.GetString("BusinessReg_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the Company provide anti-bribery/anti-corruption training to its employees?.
        /// </summary>
        public static string CompanyEthic_MY {
            get {
                return ResourceManager.GetString("CompanyEthic_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the Company does not have a code of ethics or code of conduct, did they accept to comply with DKSH Supplier CoC?.
        /// </summary>
        public static string CompanyEthic_VN {
            get {
                return ResourceManager.GetString("CompanyEthic_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity registered name in local language.
        /// </summary>
        public static string EntityNameLocal_MY {
            get {
                return ResourceManager.GetString("EntityNameLocal_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity registered name in local language.
        /// </summary>
        public static string EntityNameLocal_VN {
            get {
                return ResourceManager.GetString("EntityNameLocal_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of subsidiaries/affiliates and their respective percentage of ownership.
        /// </summary>
        public static string Ownership_MY {
            get {
                return ResourceManager.GetString("Ownership_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership - subsidiaries, affiliates (if any).
        /// </summary>
        public static string Ownership_VN {
            get {
                return ResourceManager.GetString("Ownership_VN", resourceCulture);
            }
        }
    }
}
